### ISSUE TITLE
The GitHub link to NvRTX_Caustics-4.26 is lost.

### ISSUE THREAD

**Issue by Daiqy** [MMehdiMousavi/SuperCaustics#1]
Hi @MMehdiMousavi ! I am using your excellent work to carry out my research. 
I find that [the GitHub link](https://github.com/NvRTX/UnrealEngine/tree/NvRTX_Caustics-4.26) in "Step 0: Unreal Engine" is lost (404). Could you share an updated link to Unreal Engine? 
Thanks!

**Comment by MMehdiMousavi** [comment]
Hi! 

the link is actually correct, but the repository is set to private by nvidia. I am guessing you need to be part of Epic GitHub Organization to be able to see it. Thats actually easy. You can be added by following the instructions here:

https://www.unrealengine.com/en-US/ue4-on-github

Let me know if this doesnt work. 

p.s.: i will also be uploading the core project files very soon so you can get started on using them.

**Comment by Daiqy** [comment]
Thank you very much! It does work. And looking forward to your upcoming core project files!

**Comment by Daiqy** [comment]
> Hi!
> 
> the link is actually correct, but the repository is set to private by nvidia. I am guessing you need to be part of Epic GitHub Organization to be able to see it. Thats actually easy. You can be added by following the instructions here:
> 
> https://www.unrealengine.com/en-US/ue4-on-github
> 
> Let me know if this doesnt work.
> 
> p.s.: i will also be uploading the core project files very soon so you can get started on using them.

Thank you very much! It does work. And looking forward to your upcoming core project files!

**Comment by MMehdiMousavi** [comment]
project files are uploaded! check it out and let me know if I can help!
