### ISSUE TITLE
Actor class scale resets when changed.

### ISSUE THREAD

**Issue by olkovi** [MMehdiMousavi/SuperCaustics#8]
Hello,

When I change the scale of the (glass) Actor class or its instances, the scale resets back to 1, even in viewport. Do you know why this might be?

Many thanks.

**Comment by MMehdiMousavi** [comment]
Hi, When the glass actors are instantiated, their scale is set to 1 by the function that spawns them, you can solve that by normalizing the dimensions of your glass objects before importing them into unreal

**Comment by olkovi** [comment]
Thank you. Perhaps then it would be best to expose the scale variable for the circumstance that in-viewport modification might come necessary.
